### ISSUE TITLE
Can't create custom font

### ISSUE THREAD

**Issue by sbowman** [Thraka/SadConsole#108]
I have a font file, terminal.png, that's got the same layout to the other fonts.  I created a terminal.font file, tweaked the settings to point to the terminal.png and adjust the size accordingly.  But whenever I run the game using this new font, I get the following runtime error:

```
System.Runtime.Serialization.SerializationException occurred
  HResult=0x8013150C
  Message=There was an error deserializing the object of type SadConsole.FontMaster. Encountered unexpected character 'ï'.
  Source=System.Runtime.Serialization
  StackTrace:
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(Stream stream)
   at SadConsole.Serializer.Load[T](String file, IEnumerable`1 knownTypes)
   at SadConsole.Global.LoadFont(String font)
   at SadConsole.Game.Initialize()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Salem.Game.Main(String[] args) in C:\Users\pico3\OneDrive\documents\visual studio 2017\Projects\Salem\Salem\Game.cs:line 35

Inner Exception 1:
XmlException: Encountered unexpected character 'ï'.
```

Here's my terminal.font file:

```
{
  "FilePath": "terminal.png",
  "GlyphHeight": 16,
  "GlyphPadding": 0,
  "GlyphWidth": 16,
  "Name": "terminal",
  "SolidGlyphIndex": 219
}
```

What am I doing wrong?

**Comment by Thraka** [comment]
The encoding on the file is wrong, it should be UTF-8

**Comment by sbowman** [comment]
Once I figured out how to change the encoding, VS 2017 created it as "UTF-8 with signature".  Apparently it needed to be "UTF-8 without signature".  Thanks.  I would have never figured that out. 

Bit of a gripe, but if Windows is going to be this picky about file encodings, maybe it shouldn't hide how to change them in a dropdown on the save button?

**Comment by Thraka** [comment]
There is probably something I can do about this in detecting and converting to UTF-8 somehow on load.

**Comment by tstavrianos** [comment]
This might help: https://stackoverflow.com/a/19283954

**Comment by Thraka** [comment]
Thanks!
