### ISSUE TITLE
Cannot type text into InputBox

### ISSUE THREAD

**Issue by lempamo** [Thraka/SadConsole#110]
I have this code for an input box, which is added to a Window:
```cs
            var input = new SadConsole.Controls.InputBox(32);
            input.Position = new Point(2, 3);
            input.UseKeyboard = true;
```
And when I click on it, a part of it turns brighter and a underscore flashes, like I think it should, but I cannot enter text in it for some reason. I don't know if this is a bug or if dumb me has forgot something. 😛 
But either way, I need help.

**Comment by Thraka** [comment]
Make sure that your current console hosting the textbox is set as the "active" one. Use `yourConsoleVariable.IsFocused = true;`

Only focused consoles will receive keyboard input.

**Comment by Thraka** [comment]
Sorry for the delay in responding. Work has been a bit busy.

**Comment by lempamo** [comment]
I tried doing that, but as soon as I ran my program, I got a NullReferenceException on SadConsole.Game.Instance.Run();

**Comment by lempamo** [comment]
Here's the code in my Init() method:
```cs
            Console startingConsole = new ServerSelectionConsole();
            startingConsole.IsFocused = true;

            // Set our new console as the thing to render and process
            SadConsole.Global.CurrentScreen = startingConsole;
```

**Comment by Thraka** [comment]
Can you share your code for `ServerSelectionConsole` ?

**Comment by lempamo** [comment]
```cs
   public class ServerSelectionConsole : ControlsConsole
    {
        SadConsole.Controls.InputBox input;

        public ServerSelectionConsole() : base(80, 25)
        {
            Clear();
            Fill(null, ColorAnsi.White, null);
            Fill(new Rectangle(0, 0, 80, 1), null, ColorAnsi.BlackBright, null);
            Print(0, 0, "[c:r f:ansiyellowbright] Lempamo's [c:u][c:r f:ansiwhitebright]NewsGroup Viewer");

            var serverDialog = new Window(36, 7);
            serverDialog.Theme = Themes.CyanWindowTheme;

            var label1 = new SadConsole.Controls.DrawingSurface(25, 1);
            label1.Position = new Point(2, 2);
            label1.Print(0, 0, "Enter the server address:", ColorAnsi.BlackBright);

            input = new SadConsole.Controls.InputBox(32);
            input.Position = new Point(2, 3);

            serverDialog.Add(label1);
            serverDialog.Add(input);

            var closeBtn = new SadConsole.Controls.Button(3);
            closeBtn.Text = "X";
            closeBtn.Theme = Themes.RedButtonTheme;
            closeBtn.Position = new Point(77, 0);
            closeBtn.Click += (btn, args) => SadConsole.Game.Instance.Exit();
            Add(closeBtn);

            var servList = new SadConsole.Controls.ListBox(78, 17);

            if (!File.Exists(Path.Combine(Program.appDataDir, "serverlist.cfg"))) File.WriteAllText(Path.Combine(Program.appDataDir, "serverlist.cfg"), "");
            if (File.ReadAllText(Path.Combine(Program.appDataDir, "serverlist.cfg")) != "") foreach (string s in File.ReadAllLines(Path.Combine(Program.appDataDir, "serverlist.cfg"))) servList.Items.Add(s);
            
            servList.Position = new Point(1, 3);
            Add(servList);

            Print(1, 2, "[c:r b:ansiblack]Servers:[c:u]");

            var addBtn = new SadConsole.Controls.Button(12);
            addBtn.Theme = Themes.BlueButtonTheme;
            addBtn.Text = "Add Server";
            addBtn.Position = new Point(2, 21);
            addBtn.Fill(ColorAnsi.BlueBright, ColorAnsi.Blue, null);
            addBtn.Click += (btn, args) =>
            {
                serverDialog.Title = "Add Server";
                serverDialog.Center();
                serverDialog.Show();
            };
            Add(addBtn);
        }
```

The themes are defined in another class

**Comment by Thraka** [comment]
That looks pretty fine.. What about a stack trace?

**Comment by lempamo** [comment]
Here:
```
   at SadConsole.Controls.Button.Compose()
   at SadConsole.ControlsConsole.Update(TimeSpan time)
   at SadConsole.Game.SadConsoleGameComponent.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at LemonNGV.Program.Main(String[] args) in C:\Users\lempamo\Documents\Visual Studio 2017\Projects\LempamosNGV\LempamosNGV\Program.cs:line 30
```

**Comment by Thraka** [comment]
Ahh so it's in the Compose. Can you post your theme?

**Comment by lempamo** [comment]
```cs
    public class Themes
    {
        public static SadConsole.Themes.ButtonTheme RedButtonTheme = new SadConsole.Themes.ButtonTheme();
        public static SadConsole.Themes.ButtonTheme BlueButtonTheme = new SadConsole.Themes.ButtonTheme();

        public static SadConsole.Themes.WindowTheme CyanWindowTheme = new SadConsole.Themes.WindowTheme();

        public static void InitThemes()
        {
            RedButtonTheme.Normal = new Cell(ColorAnsi.RedBright, ColorAnsi.Red);
            RedButtonTheme.MouseOver = new Cell(ColorAnsi.Red, ColorAnsi.RedBright);
            RedButtonTheme.MouseClicking = new Cell(ColorAnsi.BlackBright, ColorAnsi.Red);

            BlueButtonTheme.Normal = new Cell(ColorAnsi.BlueBright, ColorAnsi.Blue);
            BlueButtonTheme.MouseOver = new Cell(ColorAnsi.Blue, ColorAnsi.BlueBright);
            BlueButtonTheme.MouseClicking = new Cell(ColorAnsi.BlackBright, ColorAnsi.Blue);

            CyanWindowTheme.BorderStyle = new Cell(ColorAnsi.Cyan, ColorAnsi.CyanBright);
            CyanWindowTheme.FillStyle = new Cell(ColorAnsi.Cyan, ColorAnsi.CyanBright);
            CyanWindowTheme.TitleStyle = new Cell(ColorAnsi.BlackBright, ColorAnsi.CyanBright);
        }
    }
```

**Comment by lempamo** [comment]
Ok, so I added in Focused for the button themes, and my app opens again, but the InputBox still doesn't work.

**Comment by Thraka** [comment]
OK. :) I have solved your focus problem and I'm in the middle of writing out the solution. 

Standby 😁

**Comment by Thraka** [comment]
Forget what I told you to do. There are two issues you really have with focus. But first some info on how the window works.

The window has two modes for displaying, model and non-modal. Modal means that it is the main thing on the screen and everything else should be ignored for input processing. Non-modal means just show the window as a floating dialog, but let other things accept input and processing. Modal is used for dialog prompt popups and non-modal is used for status windows where.

When you `window.Show(true)` and make it modal, the system knows that you want exclusivity on this window and it darkens the background, and sets the window itself as focused. When the window is closed, it returns input focus to the previous console that had it. 

If you show the window with `window.Show()` by default it doesn't go model and focus never shifts to the window from the console. So keyboard is still processed by the console and and not the window. You want to change your `serverDialog.Show();` line to one of the following:

```csharp
serverDialog.Show(true);

// or

serverDialog.Show();
Global.FocusedConsoles.Push(serverDialog);
```

Try the `Show(true)` and see how the experience is, you probably want that. Also, add `input.IsFocused = true;` right after you have `serverDialog.Center();` and it will be ready for typing without having the user click in the box.

**Comment by lempamo** [comment]
It worked! Thanks so much :smile:
