### ISSUE TITLE
System.FormatException occurred

### ISSUE THREAD

**Issue by slinger77** [Thraka/SadConsole#114]
I just cloned the repo to my local one. I am getting the exception format error in line 104 ColoredString.Commangs.cs
The cure is to comment it. Is it the correct way of fixing it? Why is it occurring? 
Sorry that some dialogs contain Russian character. Don't know how to get rid of them. 

![image](https://user-images.githubusercontent.com/25457321/32240740-2c30f6e4-be7f-11e7-8c72-a29f21ac9068.png)

System.FormatException occurred
  HResult=0x80131537
  Message=Входная строка имела неверный формат.
  Source=SadConsole
  StackTrace:
   at SadConsole.ColoredString.Parse(String value, Int32 surfaceIndex, ISurface surface, SurfaceEditor editor, ParseCommandStacks initialBehaviors) in D:\Программинг\с\git_test\sad\SadConsole_blue\src\SadConsole.Shared\ColoredString.Commands.cs:line 104
   at SadConsole.Surfaces.SurfaceEditor.Print(Int32 x, Int32 y, String text) in D:\Программинг\с\git_test\sad\SadConsole_blue\src\SadConsole.Shared\Surfaces\SurfaceEditor.cs:line 447
   at StarterProject.CustomConsoles.StringParsingConsole..ctor() in D:\Программинг\с\git_test\sad\SadConsole_blue\src\DemoProject\SharedCode\CustomConsoles\StringParsingConsole.cs:line 42
   at StarterProject.Container..ctor() in D:\Программинг\с\git_test\sad\SadConsole_blue\src\DemoProject\SharedCode\Container.cs:line 29
   at StarterProject.Program.Init() in D:\Программинг\с\git_test\sad\SadConsole_blue\src\DemoProject\DesktopDX\Program.cs:line 89
   at SadConsole.Game.Initialize() in D:\Программинг\с\git_test\sad\SadConsole_blue\src\SadConsole.Shared\Graphics.MonoGame\Game.cs:line 111
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at StarterProject.Program.Main(String[] args) in D:\Программинг\с\git_test\sad\SadConsole_blue\src\DemoProject\DesktopDX\Program.cs:line 36

**Comment by Thraka** [comment]
This is related to your string culture. Unicode isn't supported by sadconsole yet. You need to convert the strings to UTF-8 (i think) before your send them through sadconsole. Issue #84 has reported this.

**Comment by slinger77** [comment]
Is it ok to simply comment it?

**Comment by Thraka** [comment]
yes, but it's letting you know that your string was not processed. so you will not see the printing.
