### ISSUE TITLE
Font seem not serializable (V9.00)

### ISSUE THREAD

**Issue by coldwarrl** [Thraka/SadConsole#268]
If a font file (.fnt) gets deserialized (e.g. by invoking
`  SadConsole.Game.Create(80, 25, "Res/Fonts/C64.font");`
in the FeatureDemo project), you get an exception

"Newtonsoft.Json.JsonSerializationException: Could not create an instance of type SadConsole.IFont. Type is an interface or abstract class and cannot be instantiated. Path 'FilePath', line 1, position 12.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at SadConsole.Serializer.Load[T](String file, Boolean isCompressed) in C:\Users\xxx\git\SadConsole\SadConsole\Serializer.cs:line 140
   at SadConsole.GameHost.LoadFont(String font) in C:\Users\xxx\git\SadConsole\SadConsole\GameHost.cs:line 204
   at SadConsole.GameHost.LoadDefaultFonts(String defaultFont) in C:\Users\xxx\git\SadConsole\SadConsole\GameHost.cs:line 321

**Comment by Thraka** [comment]
The fix is to specify the type in the font file now, add this as the first property of the json in the font file:
```
"$type": "SadConsole.SadFont, SadConsole",
```
For example:
```json
{
    "$type": "SadConsole.SadFont, SadConsole",
    "FilePath": "Yayo_c64.png",
    "GlyphHeight": 16,
    "GlyphPadding": 1,
    "GlyphWidth": 16,
    "Name": "C64",
    "SolidGlyphIndex": 219
}
```
